### PR TITLE
Add a CocoaPods Spec

### PR DESCRIPTION
**Pull request by czechboy0**

### CODE REVIEW

**Comment by jawr** [comment]
Please can we have a podspec in master?

**Comment by lgrzywac** [comment]
I am also waiting for this merge

**Comment by janukobytsch** [comment]
+1 for podspec, would really appreciate it!

**Comment by RLovelett** [comment]
Is it safe to say this project is languishing?

**Comment by soffes** [comment]
All of the maintainers don't use CocoaPods :)

**Comment by eliperkins** [comment]
Admittedly, I don't use CocoaPods with DVR (clearly). I'm cool with getting a podspec merged into the repo though, but it would be nice to have some way to test it out, of which I'm not sure is really easy to do.

@czechboy0: do you have interest in updating this podspec? I see your fork as an updated version of this podspec, as well as the version being at v0.3.0 now. Do you want to update this PR or should I create a new one?

**Comment by czechboy0** [comment]
Go ahead :)

**Comment by soffes** [comment]
Thanks @eliperkins! ❤️

**Pull request closed without merging**
