### PR TITLE
Session delegate (Alamofire) support - closes #11, closes #12

### LINKED ISSUE #11: Add support for data task delegate

### LINKED ISSUE #12: Add support for download task delegate

### PR DESCRIPTION
**Pull request by srdanrasic**
- Adds support for data task delegate
- Adds support for download task delegate
- Adds .gitignore
- Sets 4 space tab setting on project file

This enables DVR to work with Alamofire.

``` swift
let delegate = Manager.SessionDelegate()
let session = Session(cassetteName: "example", delegate: delegate)
let manager = Manager(session: session, delegate: delegate)
```

### CODE REVIEW

**Comment by dgdosen** [comment]
Can you clarify why you need to create and manage task ids?

**Comment by srdanrasic** [comment]
Because `NSURLSessionDataTask`/`NSURLSessionTask` does not implement `taskIdentifier` property. 

If you try executing 

``` swift
let task = NSURLSessionDataTask()
print(task.taskIdentifier)
```

your program will crash. I guess under the hood it's implemented as Objective-C `@dynamic` property.

That's why I need to handle task identifiers and other properties that I've overridden manually.

**Comment by phatmann** [comment]
Can Alamofire be used with DVR even without this PR? Supposedly [this Alamofire PR](https://github.com/Alamofire/Alamofire/pull/795) allows DVR to be used with it.

**Comment by hugobast** [comment]
@phatmann the Alamofire PR you mention is absolutely advancing the goal of DVR + Alamofire. What it does is add a failable init to configure a `Manager` with a different `Session`. That's great and it works great. On DVR's side there are things required in order to work:
- [We need to be able to set the delegate.](https://github.com/Alamofire/Alamofire/blob/master/Source/Manager.swift#L171)
- [SessionDataTask needs a taskIdentifier](https://github.com/Alamofire/Alamofire/blob/master/Source/Manager.swift#L254)

Let me know if I can do anything to advance this PR and give it a chance to be merged. It would be great to have that Alamofire supported.

**Comment by nebiros** [comment]
Got the same error as @srdanrasic:

```
"-[DVR.SessionDataTask taskIdentifier]: unrecognized selector sent to instance 0x60b000064a60"
```

**Pull request closed without merging**
