### PR TITLE
Debug status code not being recorded

### LINKED ISSUE #74: HTTP status codes not recorded when not 200.
My type used for storing errors returned by my API hold the http status code so that user's can get more information while debugging their failed requests. However, when writing acceptance tests that the correct status codes are returned, DVR simply returns HTTP status code 0 always.

It looks like the status code is not being recorded in the cassette.

Any chance we can also record the status code?

### PR DESCRIPTION
**Pull request by loudmouth**
Fixes #74 & #69 

This PR fixes a regression that caused the http status code and http headers to not be recorded in the case of non-200 responses. I've added a test to avoid future regressions.

### CODE REVIEW

**Comment by loudmouth** [comment]
This PR is ready for review @dmiluski @eliperkins

**Comment by eliperkins** [comment]
Is the fix in here? It looks like the only changes are in the test files.

**Comment by loudmouth** [comment]
Hmm, maybe it got lost during rebase...i saw that #75 was merged some time ago, but my fork was still not working. Maybe it's worthwhile to simply add this test and publish a new version?

**Comment by eliperkins** [comment]
Yeah, adding this test seems kosher to me, especially since it's passing.

**Review by eliperkins — APPROVED** [review]

**Pull request merged**
