### PR TITLE
Fixes a crash where the task is being cancelled.

### PR DESCRIPTION
**Pull request by RuiAAPeres**
Fixes this crash I am seeing while using [ReactiveCocoa #2180](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2180)

### CODE REVIEW

**Comment by czechboy0** [comment]
Link: https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2180

**Comment by soffes** [comment]
:+1: looks good to me

**Comment by RuiAAPeres** [comment]
Awesome! :ship: it?

**Comment by ayanonagon** [comment]
:green_apple:

**Pull request merged**
