### PR TITLE
Clean up test organization for SessionUploadTests

### PR DESCRIPTION
**Pull request by eliperkins**
Just some general organizational and stylistic clean up. Added XCTFails for some former force unwraps as sanity checks as well.

### CODE REVIEW

**Comment by soffes** [comment]
Personally, I prefer the brevity of force unwraps in testing. The test will still fail or crash if the force fails. :)

**Comment by eliperkins** [comment]
This is me flailing trying to figure out why tests are failing on Travis but not locally haha. Crashing because of a force unwrap somewhere only in the iOS tests...

**Comment by eliperkins** [comment]
The Travis logs aren't super helpful... https://travis-ci.org/venmo/DVR/jobs/139790798#L436

**Comment by soffes** [comment]
Ah fair. Definitely better for CI logs

**Pull request closed without merging**
